FROM us-central1-docker.pkg.dev/cloud-workstations-images/predefined/code-oss:latest

RUN sudo apt update
RUN sudo apt install -y graphviz

## Extension Pack for Java
## https://open-vsx.org/extension/vscjava/vscode-java-pack
RUN wget https://open-vsx.org/api/vscjava/vscode-java-pack/0.25.3/file/vscjava.vscode-java-pack-0.25.3.vsix && \
unzip vscjava.vscode-java-pack-0.25.3.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/java-pack

## Lombok Annotations Support for VS Code https://open-vsx.org/extension/GabrielBB/vscode-lombok
RUN wget https://open-vsx.org/api/GabrielBB/vscode-lombok/1.0.1/file/GabrielBB.vscode-lombok-1.0.1.vsix && \
unzip GabrielBB.vscode-lombok-1.0.1.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/lombok

## Quarkus https://open-vsx.org/extension/redhat/vscode-quarkus
RUN wget https://open-vsx.org/api/redhat/vscode-quarkus/1.11.0/file/redhat.vscode-quarkus-1.11.0.vsix && \
unzip redhat.vscode-quarkus-1.11.0.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/quarkus

## Dependency Analytics https://open-vsx.org/extension/redhat/fabric8-analytics
RUN wget https://open-vsx.org/api/redhat/fabric8-analytics/0.3.6/file/redhat.fabric8-analytics-0.3.6.vsix && \
unzip redhat.fabric8-analytics-0.3.6.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/fabric8-analytics

## YAML https://open-vsx.org/extension/redhat/vscode-yaml
RUN wget https://open-vsx.org/api/redhat/vscode-yaml/1.10.1/file/redhat.vscode-yaml-1.10.1.vsix && \
unzip redhat.vscode-yaml-1.10.1.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/yaml

# Linting

## SonarLint https://open-vsx.org/extension/SonarSource/sonarlint-vscode
RUN wget https://open-vsx.org/api/SonarSource/sonarlint-vscode/3.11.0/file/SonarSource.sonarlint-vscode-3.11.0.vsix && \
unzip SonarSource.sonarlint-vscode-3.11.0.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/sonarlint

# Containers and Microservices
## Docker https://open-vsx.org/extension/ms-azuretools/vscode-docker
RUN wget https://open-vsx.org/api/ms-azuretools/vscode-docker/1.22.2/file/ms-azuretools.vscode-docker-1.22.2.vsix && \
unzip ms-azuretools.vscode-docker-1.22.2.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/docker

# Workbench

## Output Colorizer https://open-vsx.org/extension/IBM/output-colorizer
RUN wget https://open-vsx.org/api/IBM/output-colorizer/0.1.2/file/IBM.output-colorizer-0.1.2.vsix && \
unzip IBM.output-colorizer-0.1.2.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/output-colorizer

## Material Icon Theme https://open-vsx.org/extension/PKief/material-icon-theme
RUN wget https://open-vsx.org/api/PKief/material-icon-theme/4.21.0/file/PKief.material-icon-theme-4.21.0.vsix && \
unzip PKief.material-icon-theme-4.21.0.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/material-icon-theme

## markdownlint https://open-vsx.org/extension/DavidAnson/vscode-markdownlint
RUN wget https://open-vsx.org/api/DavidAnson/vscode-markdownlint/0.48.1/file/DavidAnson.vscode-markdownlint-0.48.1.vsix && \
unzip DavidAnson.vscode-markdownlint-0.48.1.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/markdownlint

## Git Graph https://open-vsx.org/extension/mhutchie/git-graph
RUN wget https://open-vsx.org/api/mhutchie/git-graph/1.30.0/file/mhutchie.git-graph-1.30.0.vsix && \
unzip mhutchie.git-graph-1.30.0.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/git-graph
